Make paths generated by doc-gen4 relative.
leanprover/doc-gen4 pull request #32
Opened 2022-02-15 11:39 UTC by bollu

This obviates the need for a root URL, and follows other tools such as the Rust docs, which always generate relative paths.

Eg: `view-source:https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/dep_graph/struct.WorkProduct.html#structfield.cgu_name`

2022-02-15 18:04 UTC, hargoniX requested changes
The code looks good apart from the few nitpicks I mentioned.

Note that however this does not work fully yet, if I e.g. cd into just the `build` directory and run the python test server there, then navigate to the index page everything looks fine but as soon as you visit a subpage stuff starts going wrong. Can you reproduce this? And if yes fix it? After all that's basically the only point of this PR.

2022-02-15 18:04 UTC, hargoniX commented on Main.lean
>    let modules := args.tail!
This will no longer be correct if the first argument is already a module.

2022-02-15 18:04 UTC, hargoniX commented on DocGen4/Output/Base.lean
> +  -- root : String
No just commenting stuff out, either we remove it fully or we keep it.

2022-02-15 18:04 UTC, hargoniX commented on DocGen4/Output/Base.lean
> +-- def getRoot : HtmlM String := do pure (←read).root
Same as with the root attribute

2022-02-16 21:13 UTC, bollu commented
@hargoniX The new implementation uses `realPath` to canonicalize paths, followed up by generating relative paths. [It's live-hosted here](https://bollu.github.io/lean4_docs/Lean/Declaration.html). 

One way I can see to avoid the dependency on `realPath` is to manually set the nesting depth to the base, instead of having it be automatically computed from the distance between `basePath` and `currentPath`. However, this feels error-prone to me.

Another option, as you suggested, is to implement the subset of `realpath` canonicalization we want. This fixes it for UNIX, I'm not sure what happens on Windows.

2022-02-16 21:15 UTC, bollu commented
@hargoniX how do you suggest we proceed? I'll prototype the other approach I have in mind (manually controlling depth) in another PR, and perhaps we can compare? Or maybe there's a cleaner solution that either of these?

2022-02-21 09:11 UTC, closed without merging