Feb 21 relative paths manual depth
leanprover/doc-gen4 pull request #39
Opened 2022-02-21 09:12 UTC by bollu

Based on a discussion with @hargoniX , we decided it is simpler to manually calculate the offset to the root when generating relative paths. This supersedes #32 , which calculates nesting depth by normalizing paths via `unsafePerformIO`+`realpath`.

2022-02-21 17:21 UTC, hargoniX commented on DocGen4/Output.lean
> +  let basePath := FilePath.mk "./build/doc/"
We should leave this like in the original with the operating systems path separator just in case Windows has some special feelings about this.

2022-02-21 17:22 UTC, hargoniX commented on Main.lean
> +    IO.println "Usage: doc-gen4 Module1 Module2 ..."
We should also update the README accordingly.

2022-02-21 17:27 UTC, hargoniX requested changes
Furthermore since you changed the way the CLI works you'll also have to change the way the CI runs now, otherwise it will fail with an unknown package "/", apart from that looks good to me!

2022-04-07 00:09 UTC, bollu commented
@hargoniX I request another round of review, as I've updated the PR to the latest version. I rebuilt https://bollu.github.io/lean4_docs/ with the new PR, and nothing seems to be broken :tm: :)

2022-04-07 06:29 UTC, merged

2022-04-07 09:26 UTC, bollu commented
@Kha I'm unsure why that's happening. It seems to work here: 

https://bollu.github.io/lean4_docs/Init/Prelude.html#Nat

Let me take a look.

2022-04-07 09:45 UTC, hargoniX commented
I figured the culprit: If you run this in a local configuration the request for the JSON file we use to figure out the location of stuff is not cached and you will actually see it fail since it's looking up the file in the wrong directory now because the path to it is constructed wrongly. When the request is cached however (like in the case of Github pages) you will instead be provided with an outdated locations file that will then get processed wrong and thus you get redirected in the wrong way.

2022-04-07 09:50 UTC, hargoniX commented
Hm...now it doesn't occur anymore? Maybe I was seeing some other weird issue then...

2022-04-07 10:11 UTC, hargoniX commented
So there are actually multiple things with the search wrong here that don't occur on your page:
- The thing Kha described
- If you visit a subdirectory say this one: https://leanprover-community.github.io/mathlib4_docs/Mathlib/Control/Random.html and try to search it won't find the JSON bmp file anymore because the JS is in fact completely unaware of the relative root stuff and will thus search in the wrong directory

This leads me to believe that your page is not hosting a current build, otherwise the JS should be looking in the same path as here which it is definitely not doing, which would also explain why stuff works on your host and not on the others. The correct solution for this is IMO to teach the JS in every HTML about the correct relative site root relative to the current HTML file so it can find the JSON file correctly in the first place.

The second step would be to change the JSON file generator so that the file always contains absolute instead of relative URLs and then append the current relative site root to the search suggestions that we can get out of it.